database:
  host: localhost
  user: postgres
  password: 244159
  dbname: postgres
  port: 5432
  sslmode: disable
  timezone: Asia/Shanghai
server:
  port: ":8088"
  read_timeout: 10  # in seconds
  write_timeout: 10 # in seconds
  max_header_bytes: 1048576  # 1 MB